name: tests
on: [push, pull_request]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'poetry'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: install dependencies
        run: make .make/deps .make/test-deps
      - name: run tests and generate coverage report
        run: make .make/run-tests coverage.xml
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      - name: save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Build package
        run: poetry build
      - name: save package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  upload-coverage:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: retrieve coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true

